/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Up3FrRouteImport } from './routes/up3-fr'
import { Route as Up3BackRouteImport } from './routes/up3-back'
import { Route as Up2FrRouteImport } from './routes/up2-fr'
import { Route as Up2BackRouteImport } from './routes/up2-back'
import { Route as Up1FrRouteImport } from './routes/up1-fr'
import { Route as Up1BackRouteImport } from './routes/up1-back'
import { Route as Up1RouteImport } from './routes/up1'
import { Route as PresselRouteImport } from './routes/pressel'
import { Route as Obrigado4RouteImport } from './routes/obrigado4'
import { Route as Obrigado3RouteImport } from './routes/obrigado3'
import { Route as Obrigado2RouteImport } from './routes/obrigado2'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as EnvioEmailsRouteImport } from './routes/envio-emails'
import { Route as EntregavelRouteImport } from './routes/entregavel'
import { Route as BackRedirectRouteImport } from './routes/back-redirect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicEmailOpenRouteImport } from './routes/api/public/email-open'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicCooudWebhookRouteImport } from './routes/api/public/cooud/webhook'
import { Route as ApiPublicCooudPaymentEventRouteImport } from './routes/api/public/cooud/payment-event'
import { Route as ApiPublicCooudCheckoutRouteImport } from './routes/api/public/cooud/checkout'

const Up3FrRoute = Up3FrRouteImport.update({
  id: '/up3-fr',
  path: '/up3-fr',
  getParentRoute: () => rootRouteImport,
} as any)
const Up3BackRoute = Up3BackRouteImport.update({
  id: '/up3-back',
  path: '/up3-back',
  getParentRoute: () => rootRouteImport,
} as any)
const Up2FrRoute = Up2FrRouteImport.update({
  id: '/up2-fr',
  path: '/up2-fr',
  getParentRoute: () => rootRouteImport,
} as any)
const Up2BackRoute = Up2BackRouteImport.update({
  id: '/up2-back',
  path: '/up2-back',
  getParentRoute: () => rootRouteImport,
} as any)
const Up1FrRoute = Up1FrRouteImport.update({
  id: '/up1-fr',
  path: '/up1-fr',
  getParentRoute: () => rootRouteImport,
} as any)
const Up1BackRoute = Up1BackRouteImport.update({
  id: '/up1-back',
  path: '/up1-back',
  getParentRoute: () => rootRouteImport,
} as any)
const Up1Route = Up1RouteImport.update({
  id: '/up1',
  path: '/up1',
  getParentRoute: () => rootRouteImport,
} as any)
const PresselRoute = PresselRouteImport.update({
  id: '/pressel',
  path: '/pressel',
  getParentRoute: () => rootRouteImport,
} as any)
const Obrigado4Route = Obrigado4RouteImport.update({
  id: '/obrigado4',
  path: '/obrigado4',
  getParentRoute: () => rootRouteImport,
} as any)
const Obrigado3Route = Obrigado3RouteImport.update({
  id: '/obrigado3',
  path: '/obrigado3',
  getParentRoute: () => rootRouteImport,
} as any)
const Obrigado2Route = Obrigado2RouteImport.update({
  id: '/obrigado2',
  path: '/obrigado2',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvioEmailsRoute = EnvioEmailsRouteImport.update({
  id: '/envio-emails',
  path: '/envio-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregavelRoute = EntregavelRouteImport.update({
  id: '/entregavel',
  path: '/entregavel',
  getParentRoute: () => rootRouteImport,
} as any)
const BackRedirectRoute = BackRedirectRouteImport.update({
  id: '/back-redirect',
  path: '/back-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmailOpenRoute = ApiPublicEmailOpenRouteImport.update({
  id: '/api/public/email-open',
  path: '/api/public/email-open',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCooudWebhookRoute = ApiPublicCooudWebhookRouteImport.update({
  id: '/api/public/cooud/webhook',
  path: '/api/public/cooud/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCooudPaymentEventRoute =
  ApiPublicCooudPaymentEventRouteImport.update({
    id: '/api/public/cooud/payment-event',
    path: '/api/public/cooud/payment-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCooudCheckoutRoute = ApiPublicCooudCheckoutRouteImport.update({
  id: '/api/public/cooud/checkout',
  path: '/api/public/cooud/checkout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/back-redirect': typeof BackRedirectRoute
  '/entregavel': typeof EntregavelRoute
  '/envio-emails': typeof EnvioEmailsRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/obrigado3': typeof Obrigado3Route
  '/obrigado4': typeof Obrigado4Route
  '/pressel': typeof PresselRoute
  '/up1': typeof Up1Route
  '/up1-back': typeof Up1BackRoute
  '/up1-fr': typeof Up1FrRoute
  '/up2-back': typeof Up2BackRoute
  '/up2-fr': typeof Up2FrRoute
  '/up3-back': typeof Up3BackRoute
  '/up3-fr': typeof Up3FrRoute
  '/api/public/email-open': typeof ApiPublicEmailOpenRoute
  '/api/public/cooud/checkout': typeof ApiPublicCooudCheckoutRoute
  '/api/public/cooud/payment-event': typeof ApiPublicCooudPaymentEventRoute
  '/api/public/cooud/webhook': typeof ApiPublicCooudWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/back-redirect': typeof BackRedirectRoute
  '/entregavel': typeof EntregavelRoute
  '/envio-emails': typeof EnvioEmailsRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/obrigado3': typeof Obrigado3Route
  '/obrigado4': typeof Obrigado4Route
  '/pressel': typeof PresselRoute
  '/up1': typeof Up1Route
  '/up1-back': typeof Up1BackRoute
  '/up1-fr': typeof Up1FrRoute
  '/up2-back': typeof Up2BackRoute
  '/up2-fr': typeof Up2FrRoute
  '/up3-back': typeof Up3BackRoute
  '/up3-fr': typeof Up3FrRoute
  '/api/public/email-open': typeof ApiPublicEmailOpenRoute
  '/api/public/cooud/checkout': typeof ApiPublicCooudCheckoutRoute
  '/api/public/cooud/payment-event': typeof ApiPublicCooudPaymentEventRoute
  '/api/public/cooud/webhook': typeof ApiPublicCooudWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/back-redirect': typeof BackRedirectRoute
  '/entregavel': typeof EntregavelRoute
  '/envio-emails': typeof EnvioEmailsRoute
  '/obrigado': typeof ObrigadoRoute
  '/obrigado2': typeof Obrigado2Route
  '/obrigado3': typeof Obrigado3Route
  '/obrigado4': typeof Obrigado4Route
  '/pressel': typeof PresselRoute
  '/up1': typeof Up1Route
  '/up1-back': typeof Up1BackRoute
  '/up1-fr': typeof Up1FrRoute
  '/up2-back': typeof Up2BackRoute
  '/up2-fr': typeof Up2FrRoute
  '/up3-back': typeof Up3BackRoute
  '/up3-fr': typeof Up3FrRoute
  '/api/public/email-open': typeof ApiPublicEmailOpenRoute
  '/api/public/cooud/checkout': typeof ApiPublicCooudCheckoutRoute
  '/api/public/cooud/payment-event': typeof ApiPublicCooudPaymentEventRoute
  '/api/public/cooud/webhook': typeof ApiPublicCooudWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/back-redirect'
    | '/entregavel'
    | '/envio-emails'
    | '/obrigado'
    | '/obrigado2'
    | '/obrigado3'
    | '/obrigado4'
    | '/pressel'
    | '/up1'
    | '/up1-back'
    | '/up1-fr'
    | '/up2-back'
    | '/up2-fr'
    | '/up3-back'
    | '/up3-fr'
    | '/api/public/email-open'
    | '/api/public/cooud/checkout'
    | '/api/public/cooud/payment-event'
    | '/api/public/cooud/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/back-redirect'
    | '/entregavel'
    | '/envio-emails'
    | '/obrigado'
    | '/obrigado2'
    | '/obrigado3'
    | '/obrigado4'
    | '/pressel'
    | '/up1'
    | '/up1-back'
    | '/up1-fr'
    | '/up2-back'
    | '/up2-fr'
    | '/up3-back'
    | '/up3-fr'
    | '/api/public/email-open'
    | '/api/public/cooud/checkout'
    | '/api/public/cooud/payment-event'
    | '/api/public/cooud/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/back-redirect'
    | '/entregavel'
    | '/envio-emails'
    | '/obrigado'
    | '/obrigado2'
    | '/obrigado3'
    | '/obrigado4'
    | '/pressel'
    | '/up1'
    | '/up1-back'
    | '/up1-fr'
    | '/up2-back'
    | '/up2-fr'
    | '/up3-back'
    | '/up3-fr'
    | '/api/public/email-open'
    | '/api/public/cooud/checkout'
    | '/api/public/cooud/payment-event'
    | '/api/public/cooud/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackRedirectRoute: typeof BackRedirectRoute
  EntregavelRoute: typeof EntregavelRoute
  EnvioEmailsRoute: typeof EnvioEmailsRoute
  ObrigadoRoute: typeof ObrigadoRoute
  Obrigado2Route: typeof Obrigado2Route
  Obrigado3Route: typeof Obrigado3Route
  Obrigado4Route: typeof Obrigado4Route
  PresselRoute: typeof PresselRoute
  Up1Route: typeof Up1Route
  Up1BackRoute: typeof Up1BackRoute
  Up1FrRoute: typeof Up1FrRoute
  Up2BackRoute: typeof Up2BackRoute
  Up2FrRoute: typeof Up2FrRoute
  Up3BackRoute: typeof Up3BackRoute
  Up3FrRoute: typeof Up3FrRoute
  ApiPublicEmailOpenRoute: typeof ApiPublicEmailOpenRoute
  ApiPublicCooudCheckoutRoute: typeof ApiPublicCooudCheckoutRoute
  ApiPublicCooudPaymentEventRoute: typeof ApiPublicCooudPaymentEventRoute
  ApiPublicCooudWebhookRoute: typeof ApiPublicCooudWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/up3-fr': {
      id: '/up3-fr'
      path: '/up3-fr'
      fullPath: '/up3-fr'
      preLoaderRoute: typeof Up3FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up3-back': {
      id: '/up3-back'
      path: '/up3-back'
      fullPath: '/up3-back'
      preLoaderRoute: typeof Up3BackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up2-fr': {
      id: '/up2-fr'
      path: '/up2-fr'
      fullPath: '/up2-fr'
      preLoaderRoute: typeof Up2FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up2-back': {
      id: '/up2-back'
      path: '/up2-back'
      fullPath: '/up2-back'
      preLoaderRoute: typeof Up2BackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up1-fr': {
      id: '/up1-fr'
      path: '/up1-fr'
      fullPath: '/up1-fr'
      preLoaderRoute: typeof Up1FrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up1-back': {
      id: '/up1-back'
      path: '/up1-back'
      fullPath: '/up1-back'
      preLoaderRoute: typeof Up1BackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/up1': {
      id: '/up1'
      path: '/up1'
      fullPath: '/up1'
      preLoaderRoute: typeof Up1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pressel': {
      id: '/pressel'
      path: '/pressel'
      fullPath: '/pressel'
      preLoaderRoute: typeof PresselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado4': {
      id: '/obrigado4'
      path: '/obrigado4'
      fullPath: '/obrigado4'
      preLoaderRoute: typeof Obrigado4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado3': {
      id: '/obrigado3'
      path: '/obrigado3'
      fullPath: '/obrigado3'
      preLoaderRoute: typeof Obrigado3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado2': {
      id: '/obrigado2'
      path: '/obrigado2'
      fullPath: '/obrigado2'
      preLoaderRoute: typeof Obrigado2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/envio-emails': {
      id: '/envio-emails'
      path: '/envio-emails'
      fullPath: '/envio-emails'
      preLoaderRoute: typeof EnvioEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregavel': {
      id: '/entregavel'
      path: '/entregavel'
      fullPath: '/entregavel'
      preLoaderRoute: typeof EntregavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/back-redirect': {
      id: '/back-redirect'
      path: '/back-redirect'
      fullPath: '/back-redirect'
      preLoaderRoute: typeof BackRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/email-open': {
      id: '/api/public/email-open'
      path: '/api/public/email-open'
      fullPath: '/api/public/email-open'
      preLoaderRoute: typeof ApiPublicEmailOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cooud/webhook': {
      id: '/api/public/cooud/webhook'
      path: '/api/public/cooud/webhook'
      fullPath: '/api/public/cooud/webhook'
      preLoaderRoute: typeof ApiPublicCooudWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cooud/payment-event': {
      id: '/api/public/cooud/payment-event'
      path: '/api/public/cooud/payment-event'
      fullPath: '/api/public/cooud/payment-event'
      preLoaderRoute: typeof ApiPublicCooudPaymentEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cooud/checkout': {
      id: '/api/public/cooud/checkout'
      path: '/api/public/cooud/checkout'
      fullPath: '/api/public/cooud/checkout'
      preLoaderRoute: typeof ApiPublicCooudCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackRedirectRoute: BackRedirectRoute,
  EntregavelRoute: EntregavelRoute,
  EnvioEmailsRoute: EnvioEmailsRoute,
  ObrigadoRoute: ObrigadoRoute,
  Obrigado2Route: Obrigado2Route,
  Obrigado3Route: Obrigado3Route,
  Obrigado4Route: Obrigado4Route,
  PresselRoute: PresselRoute,
  Up1Route: Up1Route,
  Up1BackRoute: Up1BackRoute,
  Up1FrRoute: Up1FrRoute,
  Up2BackRoute: Up2BackRoute,
  Up2FrRoute: Up2FrRoute,
  Up3BackRoute: Up3BackRoute,
  Up3FrRoute: Up3FrRoute,
  ApiPublicEmailOpenRoute: ApiPublicEmailOpenRoute,
  ApiPublicCooudCheckoutRoute: ApiPublicCooudCheckoutRoute,
  ApiPublicCooudPaymentEventRoute: ApiPublicCooudPaymentEventRoute,
  ApiPublicCooudWebhookRoute: ApiPublicCooudWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
